"""Generate the MonsterImage -> (LibraryFile, body shape) table from the C# client source.
Run from repo root: python3 rust/tools/gen_monster_table.py > rust/crates/mir-client/src/monster_table.rs
"""
import re, sys, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
enum_src = (root/'LibraryCore/Enum.cs').read_text(encoding='utf-8', errors='replace')
libs_src = (root/'LibraryCore/Libraries.cs').read_text(encoding='utf-8', errors='replace')
mon_src = (root/'Client/Models/MonsterObject.cs').read_text(encoding='utf-8', errors='replace')

def parse_enum(src, name):
    m = re.search(r'enum\s+'+name+r'\b[^{]*\{(.*?)\n\s*\}', src, re.S)
    body = m.group(1)
    body = re.sub(r'//.*', '', body)
    body = re.sub(r'\[[^\]]*\]', '', body)
    vals = {}
    cur = -1
    for tok in body.split(','):
        tok = tok.strip()
        if not tok: continue
        if '=' in tok:
            k, v = [t.strip() for t in tok.split('=')]
            cur = int(v, 0)
        else:
            k = tok; cur += 1
        vals[k] = cur
    return vals

monster_image = parse_enum(enum_src, 'MonsterImage')
library_file = parse_enum(enum_src, 'LibraryFile') if 'enum LibraryFile' in enum_src else parse_enum(libs_src, 'LibraryFile')

# Library file paths
paths = dict(re.findall(r'\[LibraryFile\.(\w+)\]\s*=\s*@?"([^"]+)"', libs_src))

# Parse the big switch in MonsterObject constructor
cases = re.findall(r'((?:\s*case MonsterImage\.\w+:\s*)+)(.*?)break;', mon_src, re.S)
table = {}
for labels, body in cases:
    names = re.findall(r'MonsterImage\.(\w+)', labels)
    lib = re.search(r'LibraryFile\.(\w+),\s*out BodyLibrary', body)
    shape = re.search(r'BodyShape\s*=\s*(-?\d+)', body)
    if not lib: continue
    for n in names:
        if n in monster_image:
            table[monster_image[n]] = (library_file[lib.group(1)], int(shape.group(1)) if shape else 0, n, lib.group(1))

print('//! Generated by rust/tools/gen_monster_table.py from Client/Models/MonsterObject.cs. Do not edit.')
print('//! Maps a Zircon `MonsterImage` value to (LibraryFile value, body shape).')
print()
print('pub fn monster_sprite(image: u16) -> Option<(u16, u16)> {')
print('    Some(match image {')
for v in sorted(table):
    lib, shape, name, libname = table[v]
    print(f'        {v} => ({lib}, {shape}), // {name} -> {libname}')
print('        _ => return None,')
print('    })')
print('}')
print()
print('/// Zircon `LibraryFile` value -> path relative to the client root (backslashes normalised).')
print('pub fn library_path(file: u16) -> Option<&\'static str> {')
print('    Some(match file {')
for name, v in sorted(library_file.items(), key=lambda kv: kv[1]):
    if name in paths:
        print(f'        {v} => "{paths[name].replace(chr(92), "/")}", // {name}')
print('        _ => return None,')
print('    })')
print('}')
print(f'// {len(table)} monster images, {len(paths)} library paths', file=sys.stderr)
