[package]
name = "zircon-patchmgr"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Zircon patch manager CLI — creates and manages client patch files"

[[bin]]
name = "zircon-patchmgr"
path = "src/main.rs"

[[bin]]
name = "zircon-patcher"
path = "src/patcher.rs"

[dependencies]
anyhow  = { workspace = true }
clap    = { version = "4", features = ["derive"] }
flate2  = "1"
md5     = "0.7"
rayon   = "1"
walkdir = "2"
